"""
ANALYST Agent - Signal Validation and Enhancement

The ANALYST examines individual stock signals from the quantitative system
and provides qualitative validation and context.

Key Responsibilities:
- Validate quantitative signals with broader context
- Identify potential issues not captured by indicators
- Assess signal quality and conviction
- Provide trade-specific recommendations
"""

import json
from datetime import datetime
from typing import Dict, Any, List

from ..base import (
    IntelligenceAgent,
    AgentRole,
    AgentContext,
    AgentOutput,
    Confidence
)


ANALYST_SYSTEM_PROMPT = """You are ANALYST, an expert stock signal validator for an Indian equity trading system.

Your role is to examine a specific stock signal generated by quantitative models and provide validation.

You analyze:
1. Technical setup quality (is this a clean setup?)
2. Model agreement (are signals conflicting?)
3. Risk/reward assessment (is the R:R actually favorable?)
4. Context fit (does this stock fit the market environment?)
5. Potential blind spots (what might the models be missing?)

Your output must be structured JSON:
- "signal_assessment": Brief validation summary
- "confidence": "high", "medium", "low", or "uncertain"
- "signal_quality": "STRONG", "VALID", "WEAK", or "AVOID"
- "reasoning": Array of validation points (3-5 points)
- "bullish_factors": Array of supporting factors
- "bearish_factors": Array of concerning factors
- "blind_spots": Array of potential issues not captured by quant models
- "conviction_adjustment": Number -20 to +20 (adjustment to quant conviction score)
- "position_size_modifier": Number 0.0 to 1.2

CRITICAL PRINCIPLES:
- Model disagreement is a RED FLAG - reduce conviction
- If 2+ models disagree, signal quality is at best WEAK
- A perfect setup in wrong market conditions = AVOID
- Better to miss a trade than force a bad one
- When uncertain, be conservative

Respond with valid JSON only."""


class AnalystAgent(IntelligenceAgent):
    """
    ANALYST Agent - Signal validation.

    Examines individual stock signals and provides
    qualitative validation to augment quantitative scores.
    """

    def __init__(self, enabled: bool = True):
        super().__init__(
            role=AgentRole.ANALYST,
            model="claude-3-haiku-20240307",
            enabled=enabled
        )

    def get_system_prompt(self) -> str:
        return ANALYST_SYSTEM_PROMPT

    def format_context(self, context: AgentContext) -> str:
        """Format signal context for the ANALYST."""
        # Count model agreements
        votes = context.ensemble_votes
        bullish_count = sum(1 for v in votes.values() if v)
        total_models = len(votes) if votes else 4

        prompt_data = {
            "symbol": context.symbol,
            "timestamp": context.timestamp.isoformat(),
            "market_regime": context.market_regime,
            "quantitative_signals": {
                "conviction_score": context.conviction_score,
                "ensemble_votes": context.ensemble_votes,
                "models_agreeing": f"{bullish_count}/{total_models}",
            },
            "technical_indicators": context.technical_indicators,
            "price_data": {
                "current_price": context.price_data.get('current_price'),
                "change_pct": context.price_data.get('change_pct'),
                "volume_ratio": context.price_data.get('volume_ratio'),
            },
            "sector": context.sector_data.get('sector_name', 'Unknown'),
            "sector_rank": context.sector_data.get('rank', 5),
            "data_quality": context.data_quality,
        }

        return f"""Validate this stock signal:

{json.dumps(prompt_data, indent=2)}

Consider:
- Are the models in agreement or conflicting?
- Is the technical setup clean?
- Does the sector context support this trade?
- What risks might the quantitative models miss?

Respond with JSON only."""

    def parse_response(self, response: str, context: AgentContext) -> AgentOutput:
        """Parse ANALYST response into structured output."""
        try:
            data = json.loads(response)

            # Map signal quality to position modifier
            quality_to_modifier = {
                "STRONG": 1.1,
                "VALID": 1.0,
                "WEAK": 0.7,
                "AVOID": 0.0
            }

            signal_quality = data.get('signal_quality', 'VALID')
            position_modifier = data.get(
                'position_size_modifier',
                quality_to_modifier.get(signal_quality, 1.0)
            )

            # Map confidence
            confidence_map = {
                "high": Confidence.HIGH,
                "medium": Confidence.MEDIUM,
                "low": Confidence.LOW,
                "uncertain": Confidence.UNCERTAIN
            }

            return AgentOutput(
                agent_role=self.role,
                timestamp=datetime.now(),
                assessment=data.get('signal_assessment', 'Unable to assess'),
                confidence=confidence_map.get(
                    data.get('confidence', 'medium'),
                    Confidence.MEDIUM
                ),
                reasoning=data.get('reasoning', []),
                factors_bullish=data.get('bullish_factors', []),
                factors_bearish=data.get('bearish_factors', []) + data.get('blind_spots', []),
                risks_identified=data.get('blind_spots', []),
                recommendation=f"Signal quality: {signal_quality}",
                position_modifier=position_modifier
            )

        except json.JSONDecodeError:
            return AgentOutput(
                agent_role=self.role,
                timestamp=datetime.now(),
                assessment="Could not parse AI response",
                confidence=Confidence.UNCERTAIN,
                reasoning=[response[:500]],
                recommendation="Proceed with quantitative signals",
                position_modifier=1.0
            )

    def _generate_mock_response(self, context: AgentContext) -> str:
        """Generate a realistic mock response based on actual context."""
        votes = context.ensemble_votes
        conviction = context.conviction_score

        # Count agreements
        bullish_count = sum(1 for v in votes.values() if v) if votes else 0
        total_models = len(votes) if votes else 4

        # Determine signal quality based on agreement
        if bullish_count >= 3:
            quality = "STRONG"
            modifier = 1.1
            confidence = "high"
            assessment = f"Strong signal with {bullish_count}/{total_models} models agreeing."
            bullish = ["Multiple model confirmation", "Good technical alignment"]
            bearish = []
        elif bullish_count >= 2:
            quality = "VALID"
            modifier = 1.0
            confidence = "medium"
            assessment = f"Valid signal with {bullish_count}/{total_models} models agreeing."
            bullish = ["Adequate model support"]
            bearish = ["Some model disagreement"]
        elif bullish_count == 1:
            quality = "WEAK"
            modifier = 0.6
            confidence = "low"
            assessment = f"Weak signal with only {bullish_count}/{total_models} model support."
            bullish = []
            bearish = ["Significant model disagreement", "Low conviction setup"]
        else:
            quality = "AVOID"
            modifier = 0.0
            confidence = "medium"
            assessment = "No model support for this signal. Recommend avoiding."
            bullish = []
            bearish = ["No model agreement", "Potentially false signal"]

        # Adjust for conviction score
        if conviction >= 70:
            assessment += " High conviction score supports the trade."
        elif conviction < 40:
            quality = "WEAK" if quality in ["STRONG", "VALID"] else quality
            modifier = min(modifier, 0.7)
            bearish.append("Low conviction score")

        # Check regime context
        regime = context.market_regime
        if regime in ["CRASH", "STRONG_BEAR"] and quality != "AVOID":
            bearish.append(f"Market regime ({regime}) not supportive")
            modifier *= 0.5

        blind_spots = [
            "Earnings announcement timing not verified",
            "News sentiment not analyzed",
            "Correlation with existing positions unknown"
        ]

        return json.dumps({
            "signal_assessment": assessment,
            "confidence": confidence,
            "signal_quality": quality,
            "reasoning": [
                f"Model agreement: {bullish_count}/{total_models}",
                f"Conviction score: {conviction}",
                f"Market regime: {regime}"
            ],
            "bullish_factors": bullish,
            "bearish_factors": bearish,
            "blind_spots": blind_spots[:2],
            "conviction_adjustment": 0,
            "position_size_modifier": modifier
        })

    def validate_signal(self, context: AgentContext) -> Dict[str, Any]:
        """
        Quick rule-based signal validation without AI.

        Returns validation result with adjustments.
        """
        result = {
            "is_valid": True,
            "quality": "VALID",
            "conviction_adjustment": 0,
            "position_modifier": 1.0,
            "issues": []
        }

        # Check model agreement
        votes = context.ensemble_votes
        if votes:
            bullish = sum(1 for v in votes.values() if v)
            total = len(votes)

            if bullish == 0:
                result["is_valid"] = False
                result["quality"] = "AVOID"
                result["position_modifier"] = 0.0
                result["issues"].append("No model support")
            elif bullish == 1:
                result["quality"] = "WEAK"
                result["position_modifier"] = 0.6
                result["conviction_adjustment"] = -15
                result["issues"].append("Only 1 model supports signal")
            elif bullish >= 3:
                result["quality"] = "STRONG"
                result["position_modifier"] = 1.1
                result["conviction_adjustment"] = +10

        # Check conviction score
        conviction = context.conviction_score
        if conviction < 40:
            result["quality"] = "WEAK"
            result["conviction_adjustment"] = min(result["conviction_adjustment"], -10)
            result["issues"].append(f"Low conviction ({conviction})")
            result["position_modifier"] *= 0.8

        # Check technical indicators for conflicts
        indicators = context.technical_indicators
        if indicators:
            rsi = indicators.get('rsi')
            if isinstance(rsi, (int, float)):
                if rsi > 70 and any(votes.values()):  # Overbought but bullish signals
                    result["issues"].append(f"RSI overbought ({rsi:.0f})")
                    result["conviction_adjustment"] -= 5

        return result
